# -*- coding: utf-8 -*-
"""color-space-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bpns-ip3PcSg2xam-RISTMUDvh1kO-ty
"""

from google.colab import drive
drive.mount('/content/gdrive')

base_dir = '/content/gdrive/My Drive/Colab Notebooks/Color Space (21.52.2116)/img/'

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread(base_dir + "face.jpeg")

img_HSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
HSV_mask = cv2.inRange(img_HSV, (0, 15, 0), (17,170,255)) 
HSV_mask = cv2.morphologyEx(HSV_mask, cv2.MORPH_OPEN, np.ones((3,3), np.uint8))

img_YCrCb = cv2.cvtColor(img, cv2.COLOR_BGR2YCrCb)
YCrCb_mask = cv2.inRange(img_YCrCb, (0, 135, 85), (255,180,135)) 
YCrCb_mask = cv2.morphologyEx(YCrCb_mask, cv2.MORPH_OPEN, np.ones((3,3), np.uint8))

global_mask=cv2.bitwise_and(YCrCb_mask,HSV_mask)
global_mask=cv2.medianBlur(global_mask,3)
global_mask = cv2.morphologyEx(global_mask, cv2.MORPH_OPEN, np.ones((4,4), np.uint8))

HSV_result = cv2.bitwise_not(HSV_mask)
YCrCb_result = cv2.bitwise_not(YCrCb_mask)
global_result = cv2.bitwise_not(global_mask)

plt.figure()
f, ax = plt.subplots(3,1) 
ax[0].imshow(HSV_result)
ax[1].imshow(YCrCb_result)
ax[2].imshow(global_result)