# -*- coding: utf-8 -*-
"""color-space-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2QLyJvnMUpTdgB_utkCpwkej6F7CpmI
"""

from google.colab import drive
drive.mount('/content/gdrive')

base_dir = '/content/gdrive/My Drive/Colab Notebooks/Color Space (21.52.2116)/img/'

import cv2
import matplotlib.pyplot as plt
import numpy as np
from google.colab.patches import cv2_imshow

im = cv2.imread(base_dir + "ikan.jpg")
cv2_imshow(im)
plt.axis('off')
plt.imshow(im)
plt.show()

im_RGB = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
plt.imshow(im_RGB)
plt.show()

R = im_RGB.copy()
R[:,:,(1,2)] = 0

G = im_RGB.copy()
G[:,:,(0,2)] = 0

B = im_RGB.copy()
B[:,:,(0,1)] = 0

fig, (ax1, ax2, ax3) = plt.subplots(1, 3)
fig.suptitle('Color channel of RGB')
ax1.imshow(R)
ax1.set_title('R Channel')
ax2.imshow(G)
ax2.set_title('G Channel')
ax3.imshow(B)
ax3.set_title('B Channel')

img_HSV = cv2.cvtColor(im, cv2.COLOR_BGR2HSV)

H = img_HSV.copy()
H[:, :, (1,2)] = 255
H_RGB = cv2.cvtColor(H, cv2.COLOR_HSV2RGB)

S = img_HSV.copy()
S[:, :, 0] = 179
S[:, :, 2] = 255
S_RGB = cv2.cvtColor(S, cv2.COLOR_HSV2RGB)

V = img_HSV.copy()
V[:, :, 0] = 179
V[:, :, 1] = 0
V_RGB = cv2.cvtColor(V, cv2.COLOR_HSV2RGB)

fig, (ax1, ax2, ax3) = plt.subplots(1, 3)
fig.suptitle('Color channel of HSV')
ax1.imshow(H_RGB)
ax1.set_title('H Channel')
ax2.imshow(S_RGB)
ax2.set_title('S Channel')
ax3.imshow(V_RGB)
ax3.set_title('V Channel')

im_Lab = cv2.cvtColor(im, cv2.COLOR_BGR2LAB)

L = im_Lab.copy()
L[:, :, (1,2)] = 0
L_RGB = cv2.cvtColor(L, cv2.COLOR_LAB2RGB)
L_GRAY = cv2.cvtColor(L_RGB, cv2.COLOR_RGB2GRAY)

a = im_Lab.copy()
a[:, :, 0] = 127
a[:, :, 2] = 0
a_RGB = cv2.cvtColor(a, cv2.COLOR_LAB2RGB)
a_GRAY = cv2.cvtColor(a_RGB, cv2.COLOR_RGB2GRAY)

import matplotlib.colors as clr
cmap_a = clr.LinearSegmentedColormap.from_list('custom blue', ['Red', 'Gray', 'Green'], N=255)

b = im_Lab.copy()
b[:, :, 0] = 127
b[:, :, 1] = 0
b_RGB = cv2.cvtColor(b, cv2.COLOR_LAB2RGB)
b_GRAY = cv2.cvtColor(b_RGB, cv2.COLOR_RGB2GRAY)

cmap_b = clr.LinearSegmentedColormap.from_list('custom blue', ['Yellow', 'Gray', 'Blue'], N=255)

fig, (ax1, ax2, ax3) = plt.subplots(1, 3)
fig.suptitle('Color channel of Gray')
ax1.imshow(L_GRAY, cmap="gray")
ax1.set_title('L Channel')
ax2.imshow(a_GRAY, cmap=cmap_a)
ax2.set_title('a Channel')
ax3.imshow(b_GRAY, cmap=cmap_b)
ax3.set_title('b Channel')

im_YCrCb = cv2.cvtColor(im, cv2.COLOR_BGR2YCrCb)

Y = im_YCrCb.copy()
Y[:, :, (1,2)] = np.max(Y)/2
Y_RGB = cv2.cvtColor(Y, cv2.COLOR_YCrCb2RGB)

Cb = im_YCrCb.copy()
Cb[:, :, (0,1)] = np.max(Cb)/2
Cb_RGB = cv2.cvtColor(Cb, cv2.COLOR_YCrCb2RGB)

Cr = im_YCrCb.copy()
Cb[:, :, (0,2)] = np.max(Cr)/2
Cr_RGB = cv2.cvtColor(Cr, cv2.COLOR_YCrCb2RGB)

fig, (ax1, ax2, ax3) = plt.subplots(1, 3)
fig.suptitle('Color channel of YCrCb')
ax1.imshow(Y_RGB)
ax1.set_title('Y Channel')
ax2.imshow(Cb_RGB)
ax2.set_title('Cb Channel')
ax3.imshow(Cr_RGB)
ax3.set_title('Cr Channel')